#include <windows.h>  // for MS Windows
#include <GL/glut.h> // GLUT, include glu.h and gl.h
#include <math.h>
#include <iostream>
#include <cstring>
#include <stdlib.h> //random-num

using namespace std;



int _angle1 = 0;
int _carMove = 0;
int _carangle = 0;
float _angle2 = 1;
int _planeMove = 0;
bool isDay = true;
bool fullscreen = true;
bool isCarMoving = true;




void handleKeypress(unsigned char key, int x, int y)
{
    switch (key)
    {
    case 'd':
        isDay = true;
        glutPostRedisplay();
        break;
    case 'n':
        isDay = false;
        glutPostRedisplay();
        break;
    case 'f': //toggle screenmode
        fullscreen = !fullscreen;
        if (fullscreen)
        {
            glutFullScreen();
        }
        else
        {
            glutReshapeWindow(600, 600);
            glutPositionWindow(0, 0);
        }
        break;
    case 'x':
        isCarMoving = !isCarMoving;
        glutPostRedisplay();
        break;
    }
}
